name: bubble
dependencies:
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- fontconfig=2.12.1=0
- freetype=2.6.3=1
- hdf5=1.8.17=7
- icu=56.1=4
- jasper=1.900.1=3
- jpeg=9b=0
- libgfortran=3.0.0=1
- libiconv=1.14=3
- libpng=1.6.24=0
- libtiff=4.0.6=6
- libxml2=2.9.4=2
- matplotlib=1.5.3=np111py35_2
- mkl=11.3.3=0
- ncurses=5.9=9
- networkx=1.11=py35_0
- numpy=1.11.2=py35_0
- opencv=3.1.0=np111py35_1
- openssl=1.0.2j=0
- pillow=3.4.1=py35_1
- pip=8.1.2=py35_0
- py=1.4.31=py35_0
- pyparsing=2.1.10=py35_0
- pyqt=4.11.4=py35_4
- pytest=3.0.3=py35_0
- python=3.5.2=2
- python-dateutil=2.5.3=py35_0
- pytz=2016.7=py35_0
- qt=4.8.6=3
- readline=6.2=2
- scikit-image=0.12.3=np111py35_1
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_1
- sqlite=3.13.0=1
- tk=8.5.19=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - bubblekicker (/home/stijn_vanhoey/githubs/project_belland_bubble_image_analysis)==0.1
  - dask==0.11.1
  - toolz==0.8.0

